In [1]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [2]:
print(arr1.shape)

(5,)


In [3]:
print(arr1.dtype)

float64


In [4]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [6]:
print(np.zeros(5))
print(np.ones(5))
print(np.empty([2,2]))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[6.  7.5]
 [8.  1. ]]


In [8]:
print(np.arange(7))

[0 1 2 3 4 5 6]


In [9]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
arr1 = np.array([1,2,3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr2.dtype)
arr3 = arr2.astype(np.float64)
print(arr3.dtype)

float64
int32
float64


In [13]:
samples = np.random.normal(size=(6,6))
print(samples)

[[ 1.88852333  0.19981905  0.19151977 -0.01568161 -1.54718649  1.29380315]
 [ 0.44382472  1.61022713  0.0267043   0.16897103  0.34821421  1.23399286]
 [ 1.10107241 -0.61190889 -0.6673071  -0.69658726 -2.4855823   2.53748176]
 [-0.90635583 -0.08440422  1.14386272  0.05918444 -2.04667094 -0.21383032]
 [-0.19198838  0.38098689 -0.46621193  0.59020509 -1.22942035 -1.88849757]
 [-0.1856362  -1.03249756 -1.11286806 -0.71890438  0.05726616  0.09513634]]
